/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import javax.swing.plaf.basic.BasicMenuBarUI;

/**
 *
 * @author Windows
 */
public class TelaAcompanhamento extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaAcompanhamento.class.getName());

    /**
     * Creates new form TelaAcompanhamento
     */
    public TelaAcompanhamento() {
        initComponents();
        
        this.getContentPane().setBackground(new java.awt.Color(198, 200, 200));
        Color corMenu = new Color(32, 32, 63); // Substitua pelo seu RGB
        MenuAcompanhamento.setBackground(corMenu);
        MenuAcompanhamento.setUI(new BasicMenuBarUI());
        MenuAcompVeiculo.setForeground(Color.WHITE);
        MenuAcompAgendamento.setForeground(Color.WHITE);
        MenuAcompLembretes.setForeground(Color.WHITE);
        MenuAcompPerfil.setForeground(Color.WHITE);
        
        this.setSize(575, 650);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnVoltar = new javax.swing.JButton();
        LblAgendamentos = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        MenuAcompanhamento = new javax.swing.JMenuBar();
        MenuAcompVeiculo = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        MenuAcompAgendamento = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        MenuAcompLembretes = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        MenuAcompPerfil = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela acompanhamento");
        setBackground(new java.awt.Color(198, 200, 200));
        setResizable(false);

        BtnVoltar.setBackground(new java.awt.Color(32, 32, 63));
        BtnVoltar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnVoltar.setForeground(new java.awt.Color(247, 250, 255));
        BtnVoltar.setText("Voltar");
        BtnVoltar.addActionListener(this::BtnVoltarActionPerformed);

        LblAgendamentos.setText("Status agendamento");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(this::jComboBox1ActionPerformed);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Status", "Data inicio", "Data fim"
            }
        ));
        jTable1.setShowGrid(true);
        jScrollPane1.setViewportView(jTable1);

        MenuAcompanhamento.setBackground(new java.awt.Color(32, 32, 63));
        MenuAcompanhamento.setForeground(new java.awt.Color(247, 250, 255));
        MenuAcompanhamento.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        MenuAcompanhamento.setOpaque(true);

        MenuAcompVeiculo.setText("Veículo");

        jMenuItem1.setText("Acessar");
        jMenuItem1.addActionListener(this::jMenuItem1ActionPerformed);
        MenuAcompVeiculo.add(jMenuItem1);

        jMenuItem2.setText("Cadastrar veículo");
        jMenuItem2.addActionListener(this::jMenuItem2ActionPerformed);
        MenuAcompVeiculo.add(jMenuItem2);

        jMenuItem3.setText("Gerenciar veículo");
        jMenuItem3.addActionListener(this::jMenuItem3ActionPerformed);
        MenuAcompVeiculo.add(jMenuItem3);

        MenuAcompanhamento.add(MenuAcompVeiculo);

        MenuAcompAgendamento.setText("Agendamento");

        jMenuItem4.setText("Acessar");
        jMenuItem4.addActionListener(this::jMenuItem4ActionPerformed);
        MenuAcompAgendamento.add(jMenuItem4);

        MenuAcompanhamento.add(MenuAcompAgendamento);

        MenuAcompLembretes.setText("Lembretes");

        jMenuItem5.setText("Acessar");
        MenuAcompLembretes.add(jMenuItem5);

        MenuAcompanhamento.add(MenuAcompLembretes);

        MenuAcompPerfil.setText("Perfil");

        jMenuItem6.setText("Acessar");
        MenuAcompPerfil.add(jMenuItem6);

        jMenuItem7.setText("Sair");
        jMenuItem7.addActionListener(this::jMenuItem7ActionPerformed);
        MenuAcompPerfil.add(jMenuItem7);

        MenuAcompanhamento.add(MenuAcompPerfil);

        setJMenuBar(MenuAcompanhamento);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnVoltar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LblAgendamentos)
                        .addGap(0, 454, Short.MAX_VALUE))
                    .addComponent(jScrollPane1)
                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(LblAgendamentos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 145, Short.MAX_VALUE)
                .addComponent(BtnVoltar)
                .addGap(61, 61, 61))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        TelaVeiculo telaVeiculos = new TelaVeiculo();
        telaVeiculos.setLocationRelativeTo(null);
        telaVeiculos.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        TelaCadastroVeiculo telaCadVei = new TelaCadastroVeiculo();
        telaCadVei.setLocationRelativeTo(null);
        telaCadVei.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        TelaVeiculo telaGerencia;
        telaGerencia = new TelaVeiculo();
        telaGerencia.setLocationRelativeTo(null);
        telaGerencia.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        TelaAgendamento telaAgenda = new TelaAgendamento();
        telaAgenda.setLocationRelativeTo(null);
        telaAgenda.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        TelaInicial telaInicio = new TelaInicial();
        telaInicio.setLocationRelativeTo(null);
        telaInicio.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void BtnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVoltarActionPerformed
        TelaPrincipalProp telaPrincipal = new TelaPrincipalProp();
        telaPrincipal.setLocationRelativeTo(null);
        telaPrincipal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnVoltarActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaAcompanhamento().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnVoltar;
    private javax.swing.JLabel LblAgendamentos;
    private javax.swing.JMenu MenuAcompAgendamento;
    private javax.swing.JMenu MenuAcompLembretes;
    private javax.swing.JMenu MenuAcompPerfil;
    private javax.swing.JMenu MenuAcompVeiculo;
    private javax.swing.JMenuBar MenuAcompanhamento;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
