/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.plaf.basic.BasicMenuBarUI;

/**
 *
 * @author ALUNO
 */
public class TelaAgendamento extends javax.swing.JFrame {

    /**
     * Creates new form TelaAgendamento
     */
    public TelaAgendamento() {
        initComponents();
        
        this.getContentPane().setBackground(new java.awt.Color(198, 200, 200));
        Color corMenu = new Color(32, 32, 63); 
        MenuAgendamento.setBackground(corMenu);
        MenuAgendamento.setUI(new BasicMenuBarUI());
        MenuAgenVeiculo.setForeground(Color.WHITE);
        MenuAgenLembretes.setForeground(Color.WHITE);
        MenuAgenPerfil.setForeground(Color.WHITE);
        
        this.setSize(575, 650);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LblOrdemServic = new javax.swing.JLabel();
        TxtOrdemServic = new javax.swing.JTextField();
        LblOficina = new javax.swing.JLabel();
        MenuOficina = new javax.swing.JComboBox<>();
        LblDataServic = new javax.swing.JLabel();
        LblTipoManut = new javax.swing.JLabel();
        MenuTipoManut = new javax.swing.JComboBox<>();
        LblServicoDesejado = new javax.swing.JLabel();
        MenuServicoDesejado = new javax.swing.JComboBox<>();
        LblObs = new javax.swing.JLabel();
        TxtObs = new javax.swing.JTextField();
        BtnSolicitar = new javax.swing.JButton();
        BtnVoltar = new javax.swing.JButton();
        MenuAgendamento = new javax.swing.JMenuBar();
        MenuAgenVeiculo = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        MenuAgenLembretes = new javax.swing.JMenu();
        MenuAgenPerfil = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(198, 200, 200));

        LblOrdemServic.setText("Ordem de serviço");

        LblOficina.setText("Oficina");

        MenuOficina.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        MenuOficina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuOficinaActionPerformed(evt);
            }
        });

        LblDataServic.setText("Data e período para o serviço");

        LblTipoManut.setText("Tipo de manutenção");

        MenuTipoManut.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        MenuTipoManut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuTipoManutActionPerformed(evt);
            }
        });

        LblServicoDesejado.setText("Serviço desejado");

        MenuServicoDesejado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        LblObs.setText("Observação do serviço");

        BtnSolicitar.setBackground(new java.awt.Color(255, 212, 59));
        BtnSolicitar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnSolicitar.setForeground(new java.awt.Color(33, 40, 68));
        BtnSolicitar.setText("Solicitar agendamento");

        BtnVoltar.setBackground(new java.awt.Color(32, 32, 63));
        BtnVoltar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnVoltar.setForeground(new java.awt.Color(255, 255, 255));
        BtnVoltar.setText("Voltar");
        BtnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnVoltar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TxtObs, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(MenuServicoDesejado, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MenuTipoManut, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MenuOficina, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TxtOrdemServic, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LblOrdemServic)
                            .addComponent(LblOficina)
                            .addComponent(LblDataServic)
                            .addComponent(LblTipoManut)
                            .addComponent(LblServicoDesejado)
                            .addComponent(LblObs))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(BtnSolicitar, javax.swing.GroupLayout.DEFAULT_SIZE, 557, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(LblOrdemServic, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtOrdemServic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LblOficina)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MenuOficina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LblDataServic)
                .addGap(30, 30, 30)
                .addComponent(LblTipoManut)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MenuTipoManut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LblServicoDesejado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MenuServicoDesejado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LblObs)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtObs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 134, Short.MAX_VALUE)
                .addComponent(BtnSolicitar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnVoltar)
                .addGap(67, 67, 67))
        );

        MenuAgendamento.setBackground(new java.awt.Color(32, 32, 63));
        MenuAgendamento.setForeground(new java.awt.Color(255, 255, 255));
        MenuAgendamento.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        MenuAgendamento.setOpaque(true);

        MenuAgenVeiculo.setText("Veículo");
        MenuAgenVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuAgenVeiculoActionPerformed(evt);
            }
        });

        jMenuItem3.setText("Acessar");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        MenuAgenVeiculo.add(jMenuItem3);

        jMenuItem4.setText("Cadastrar veículo");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        MenuAgenVeiculo.add(jMenuItem4);

        jMenuItem5.setText("Gerenciar veículo");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        MenuAgenVeiculo.add(jMenuItem5);

        MenuAgendamento.add(MenuAgenVeiculo);

        MenuAgenLembretes.setText("Lembretes");
        MenuAgendamento.add(MenuAgenLembretes);

        MenuAgenPerfil.setText("Perfil");

        jMenuItem1.setText("Acessar");
        MenuAgenPerfil.add(jMenuItem1);

        jMenuItem2.setText("Sair");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        MenuAgenPerfil.add(jMenuItem2);

        MenuAgendamento.add(MenuAgenPerfil);

        setJMenuBar(MenuAgendamento);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        TelaInicial telaInicio = new TelaInicial();
        telaInicio.setLocationRelativeTo(null);
        telaInicio.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void BtnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVoltarActionPerformed
        TelaPrincipalProp telaPrincipal = new TelaPrincipalProp();
        telaPrincipal.setLocationRelativeTo(null);
        telaPrincipal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnVoltarActionPerformed

    private void MenuAgenVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuAgenVeiculoActionPerformed
        try {
            TelaVeiculo telaGerencia;
            telaGerencia = new TelaVeiculo();
            telaGerencia.setLocationRelativeTo(null);
            telaGerencia.setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(TelaAgendamento.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_MenuAgenVeiculoActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        TelaCadastroVeiculo telaCadVei = new TelaCadastroVeiculo();
        telaCadVei.setLocationRelativeTo(null);
        telaCadVei.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        try {
            TelaVeiculo telaVeiculos = new TelaVeiculo();
            telaVeiculos.setLocationRelativeTo(null);
            telaVeiculos.setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(TelaAgendamento.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void MenuTipoManutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuTipoManutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuTipoManutActionPerformed

    private void MenuOficinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuOficinaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuOficinaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAgendamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAgendamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAgendamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAgendamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAgendamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnSolicitar;
    private javax.swing.JButton BtnVoltar;
    private javax.swing.JLabel LblDataServic;
    private javax.swing.JLabel LblObs;
    private javax.swing.JLabel LblOficina;
    private javax.swing.JLabel LblOrdemServic;
    private javax.swing.JLabel LblServicoDesejado;
    private javax.swing.JLabel LblTipoManut;
    private javax.swing.JMenu MenuAgenLembretes;
    private javax.swing.JMenu MenuAgenPerfil;
    private javax.swing.JMenu MenuAgenVeiculo;
    private javax.swing.JMenuBar MenuAgendamento;
    private javax.swing.JComboBox<String> MenuOficina;
    private javax.swing.JComboBox<String> MenuServicoDesejado;
    private javax.swing.JComboBox<String> MenuTipoManut;
    private javax.swing.JTextField TxtObs;
    private javax.swing.JTextField TxtOrdemServic;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
