
package Telas;

import AcessoDB.ModuloDbConnect;
import AcessoDB.ModuloDbDML;
import java.sql.Connection;
import java.sql.ResultSet;


public class TelaUsuPropri extends javax.swing.JFrame {

    Connection conexao = null;
    
    public TelaUsuPropri() {
        initComponents();
        conexao = ModuloDbConnect.connector();
        
        ModuloDbDML dbDML = new ModuloDbDML(conexao);
        
       try {
            String sql = "SELECT nm_proprietario, dt_nascimento, nr_cpf, ds_email, nr_telefone, ds_senha, ds_nome_usuario FROM t_aah_proprietario WHERE id_proprietario = 1";
            
            ResultSet rs = dbDML.consultarResultSet(sql); 
            
            if (rs.next()) {
                
                TxtNmCompletoPropri.setText(rs.getString("nm_proprietario"));
                TxtDtNascimentoPropri.setText(rs.getString("dt_nascimento"));
                TxtNrCPFPropri.setText(rs.getString("nr_cpf"));
                TxtDsEmailPropri.setText(rs.getString("ds_email"));
                TxtNrTelefonePropri.setText(rs.getString("nr_telefone"));
                TxtNmUsuPropri.setText(rs.getString("ds_nome_usuario"));
              } else {
                 javax.swing.JOptionPane.showMessageDialog(this, "Usuário não encontrado.");
              }

            } catch (Exception e) {
                 javax.swing.JOptionPane.showMessageDialog(this, "Erro ao carregar dados: " + e.getMessage());
                 e.printStackTrace();
}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        TxtNmUsuPropri = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TxtNmCompletoPropri = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TxtDtNascimentoPropri = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TxtNrCPFPropri = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TxtDsEmailPropri = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        TxtNrTelefonePropri = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nome de usuário:");

        TxtNmUsuPropri.setText("NmUsu");
        TxtNmUsuPropri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNmUsuPropriActionPerformed(evt);
            }
        });

        jLabel2.setText("Nome completo:");

        TxtNmCompletoPropri.setText("NmCompleto");
        TxtNmCompletoPropri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNmCompletoPropriActionPerformed(evt);
            }
        });

        jLabel3.setText("Data de nascimento:");

        TxtDtNascimentoPropri.setText("DtNascimento");
        TxtDtNascimentoPropri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtDtNascimentoPropriActionPerformed(evt);
            }
        });

        jLabel4.setText("CPF:");

        TxtNrCPFPropri.setText("NrCPF");
        TxtNrCPFPropri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNrCPFPropriActionPerformed(evt);
            }
        });

        jLabel5.setText("E-mail:");

        TxtDsEmailPropri.setText("DsEmail");
        TxtDsEmailPropri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtDsEmailPropriActionPerformed(evt);
            }
        });

        jLabel6.setText("Telefone:");

        TxtNrTelefonePropri.setText("NrTelefone");
        TxtNrTelefonePropri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNrTelefonePropriActionPerformed(evt);
            }
        });

        jButton1.setText("Editar");

        jButton2.setText("Excluir conta");

        jButton3.setText("Voltar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(TxtNmUsuPropri, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(TxtNmCompletoPropri, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(TxtDtNascimentoPropri, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(TxtNrCPFPropri, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(TxtDsEmailPropri, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(TxtNrTelefonePropri, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(283, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtNmUsuPropri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtNmCompletoPropri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtDtNascimentoPropri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtNrCPFPropri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtDsEmailPropri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtNrTelefonePropri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtNmUsuPropriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNmUsuPropriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNmUsuPropriActionPerformed

    private void TxtNmCompletoPropriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNmCompletoPropriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNmCompletoPropriActionPerformed

    private void TxtDtNascimentoPropriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtDtNascimentoPropriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtDtNascimentoPropriActionPerformed

    private void TxtNrCPFPropriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNrCPFPropriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNrCPFPropriActionPerformed

    private void TxtDsEmailPropriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtDsEmailPropriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtDsEmailPropriActionPerformed

    private void TxtNrTelefonePropriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNrTelefonePropriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNrTelefonePropriActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaUsuPropri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaUsuPropri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaUsuPropri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaUsuPropri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaUsuPropri().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TxtDsEmailPropri;
    private javax.swing.JTextField TxtDtNascimentoPropri;
    private javax.swing.JTextField TxtNmCompletoPropri;
    private javax.swing.JTextField TxtNmUsuPropri;
    private javax.swing.JTextField TxtNrCPFPropri;
    private javax.swing.JTextField TxtNrTelefonePropri;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
