/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;
import AcessoDB.*;
import java.sql.Connection;
import javax.swing.JOptionPane;

public class TelaCadastroPropri extends javax.swing.JFrame {
    
    Connection conexao = null;
    
    public boolean CamposCadastro_SaoValidos()
    {
        boolean[] validacoes = new boolean[8];
        
        for (int i = 0; i < validacoes.length; i++)
        {
            validacoes[i] = true;
            //System.out.println(validacoes[i]);
        }
        
        if ((TxtNome.getText().isEmpty() == true) || (TxtNome.getText().isBlank() == true))
        {
            JOptionPane.showMessageDialog(null, "Digite um nome válido!");
            validacoes[0] = false;
        }
        
        if ((TxtDataNasc.getText().isEmpty() == true) || (TxtDataNasc.getText().isBlank() == true))
        {
            JOptionPane.showMessageDialog(null, "Digite uma data de nascimento válida!");
            validacoes[1] = false;
        }
        
        if ((TxtCPF.getText().isEmpty() == true) || (TxtCPF.getText().isBlank() == true))
        {
            JOptionPane.showMessageDialog(null, "Digite um CPF válido!");
            validacoes[2] = false;
        }
        
        if ((TxtEmail.getText().isEmpty() == true) || (TxtEmail.getText().isBlank() == true))
        {
            JOptionPane.showMessageDialog(null, "Digite um e-mail válido!");
            validacoes[3] = false;
        }
        
        if ((TxtTelefone.getText().isEmpty() == true) || (TxtTelefone.getText().isBlank() == true))
        {
            JOptionPane.showMessageDialog(null, "Digite um telefone válido!");
            validacoes[4] = false;
        }
        
        if ((TxtNomeUsu.getText().isEmpty() == true) || (TxtNomeUsu.getText().isBlank() == true))
        {
            JOptionPane.showMessageDialog(null, "Digite um nome de usuário válido!");
            validacoes[5] = false;
        }
        
        if (((TxtSenha.getText().isEmpty() == true) || (TxtSenha.getText().isBlank() == true)) && 
                ((TxtConfSenha.getText().isEmpty() == true) || (TxtConfSenha.getText().isBlank() == true)))
        {
            JOptionPane.showMessageDialog(null, "Digite uma senha válida!");
            validacoes[6] = false;
        }
        else if (!TxtSenha.getText().equals(TxtConfSenha.getText()))
        {
            JOptionPane.showMessageDialog(null, "As senhas são diferentes! Confira a senha digita no campo 'Senha' e 'Confirme sua senha'!");
            validacoes[7] = false;
        }
        
        boolean is_valid = true;
        
        for (int i = 0; i < validacoes.length; i++)
        {
            if (validacoes[i] == false)
            {
                //System.out.println(validacoes[i]);
                is_valid = false;
            }
        }
        
        return is_valid;
    }

    /**
     * Creates new form TelaCadastroPropri
     */
    public TelaCadastroPropri() {
        initComponents();
        conexao = ModuloDbConnect.connector();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PnlCadastro = new javax.swing.JPanel();
        LblNome = new javax.swing.JLabel();
        LblDate = new javax.swing.JLabel();
        TxtNome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TxtDataNasc = new javax.swing.JTextField();
        LblCPF = new javax.swing.JLabel();
        TxtCPF = new javax.swing.JTextField();
        LblEmail = new javax.swing.JLabel();
        TxtTelefone = new javax.swing.JTextField();
        LblTelefone = new javax.swing.JLabel();
        TxtEmail = new javax.swing.JTextField();
        LblSenha = new javax.swing.JLabel();
        TxtSenha = new javax.swing.JPasswordField();
        LblConfSenha = new javax.swing.JLabel();
        TxtConfSenha = new javax.swing.JPasswordField();
        BtnCadastrar = new javax.swing.JButton();
        BtnVoltar = new javax.swing.JButton();
        TxtNomeUsu = new javax.swing.JTextField();
        LblNomeUsu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro Proprietário");
        setResizable(false);

        LblNome.setText("Insira seu nome");

        LblDate.setText("Data de nascimento");

        TxtNome.setForeground(new java.awt.Color(204, 204, 204));
        TxtNome.setText("Nome completo");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Crie uma conta no AutoHub");

        TxtDataNasc.setForeground(new java.awt.Color(204, 204, 204));
        TxtDataNasc.setText("dd/mm/aa");

        LblCPF.setText("Digite seu CPF");

        TxtCPF.setForeground(new java.awt.Color(204, 204, 204));
        TxtCPF.setText("000.000.000-00");

        LblEmail.setText("E-mail");

        TxtTelefone.setForeground(new java.awt.Color(204, 204, 204));
        TxtTelefone.setText("(00)00000-0000");

        LblTelefone.setText("Telefone");

        TxtEmail.setForeground(new java.awt.Color(204, 204, 204));
        TxtEmail.setText("seu_nome@site.com.br");
        TxtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtEmailActionPerformed(evt);
            }
        });

        LblSenha.setText("Senha");

        TxtSenha.setForeground(new java.awt.Color(204, 204, 204));
        TxtSenha.setText("jPasswordField1");

        LblConfSenha.setText("Confirme sua senha");

        TxtConfSenha.setForeground(new java.awt.Color(204, 204, 204));
        TxtConfSenha.setText("jPasswordField1");
        TxtConfSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtConfSenhaActionPerformed(evt);
            }
        });

        BtnCadastrar.setText("Cadastrar-se");
        BtnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCadastrarActionPerformed(evt);
            }
        });

        BtnVoltar.setText("Voltar");
        BtnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVoltarActionPerformed(evt);
            }
        });

        TxtNomeUsu.setForeground(new java.awt.Color(204, 204, 204));
        TxtNomeUsu.setText("usuario_07");
        TxtNomeUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNomeUsuActionPerformed(evt);
            }
        });

        LblNomeUsu.setText("Nome de usuário");

        javax.swing.GroupLayout PnlCadastroLayout = new javax.swing.GroupLayout(PnlCadastro);
        PnlCadastro.setLayout(PnlCadastroLayout);
        PnlCadastroLayout.setHorizontalGroup(
            PnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PnlCadastroLayout.createSequentialGroup()
                        .addGroup(PnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LblNome)
                            .addComponent(LblDate)
                            .addComponent(TxtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LblSenha)
                            .addComponent(TxtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LblConfSenha)
                            .addComponent(TxtConfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(BtnVoltar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BtnCadastrar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(PnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(TxtCPF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(LblCPF)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlCadastroLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(PnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlCadastroLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(104, 104, 104))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlCadastroLayout.createSequentialGroup()
                                .addGroup(PnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(LblEmail)
                                        .addComponent(TxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(TxtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(LblTelefone)))
                                .addContainerGap())))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlCadastroLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TxtNomeUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblNomeUsu))
                .addContainerGap())
        );
        PnlCadastroLayout.setVerticalGroup(
            PnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlCadastroLayout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(15, 15, 15)
                .addComponent(LblNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(LblDate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LblCPF)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(LblEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LblTelefone)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LblNomeUsu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtNomeUsu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(LblSenha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LblConfSenha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtConfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BtnCadastrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnVoltar)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnlCadastro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PnlCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 58, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVoltarActionPerformed
        TelaLoginProprietario telaLogin = new TelaLoginProprietario();
        telaLogin.setLocationRelativeTo(null);
        telaLogin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnVoltarActionPerformed

    private void BtnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCadastrarActionPerformed
        if (CamposCadastro_SaoValidos() == true)
        {
            ModuloDbDML db = new ModuloDbDML(conexao);
            
            long novo_id = db.inserirRetornandoId("INSERT INTO t_aah_proprietario "
                    + "(nm_proprietario, dt_nascimento, nr_cpf, ds_email, nr_telefone, ds_senha, ds_nome_usuario) "
                    + "VALUES (?, ?, ?, ?, ?, ?, ?)", 
                    TxtNome.getText(), TxtDataNasc.getText(), TxtCPF.getText(), TxtEmail.getText(), TxtTelefone.getText(), TxtSenha.getText(), TxtNomeUsu.getText());
            
            if (novo_id != -1) 
            {
                JOptionPane.showMessageDialog(null, "Cadastro do usuário " + TxtNome.getText() + " efetuado com sucesso!");
                System.out.println(novo_id);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Campo(s) inválido(s)! Corrija e tente novamente!");
        }
    }//GEN-LAST:event_BtnCadastrarActionPerformed

    private void TxtConfSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtConfSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtConfSenhaActionPerformed

    private void TxtNomeUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNomeUsuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNomeUsuActionPerformed

    private void TxtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtEmailActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroPropri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroPropri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroPropri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroPropri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroPropri().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCadastrar;
    private javax.swing.JButton BtnVoltar;
    private javax.swing.JLabel LblCPF;
    private javax.swing.JLabel LblConfSenha;
    private javax.swing.JLabel LblDate;
    private javax.swing.JLabel LblEmail;
    private javax.swing.JLabel LblNome;
    private javax.swing.JLabel LblNomeUsu;
    private javax.swing.JLabel LblSenha;
    private javax.swing.JLabel LblTelefone;
    private javax.swing.JPanel PnlCadastro;
    private javax.swing.JTextField TxtCPF;
    private javax.swing.JPasswordField TxtConfSenha;
    private javax.swing.JTextField TxtDataNasc;
    private javax.swing.JTextField TxtEmail;
    private javax.swing.JTextField TxtNome;
    private javax.swing.JTextField TxtNomeUsu;
    private javax.swing.JPasswordField TxtSenha;
    private javax.swing.JTextField TxtTelefone;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
