/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

import java.awt.Color;
import javax.swing.plaf.basic.BasicMenuBarUI;

/**
 *
 * @author ALUNO
 */
public class TelaPrincipalPresta extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipalPresta
     * @param LblNomeUsuPresta
     */
    public TelaPrincipalPresta(String LblNomeUsuPresta) {
        initComponents();
        
        this.getContentPane().setBackground(new Color(198, 200, 200));
        Color corMenu = new Color(32, 32, 63); 
        MenuPrincipalPresta.setBackground(corMenu);
        MenuPrincipalPresta.setUI(new BasicMenuBarUI());
        MenuPrincipalPrestaSolici.setForeground(Color.WHITE);
        MenuPrincipalPrestaAgenda.setForeground(Color.WHITE);
        MenuPrincipalPrestaLembretes.setForeground(Color.WHITE);
        MenuPrincipalPrestaPerfil.setForeground(Color.WHITE);
        
        this.LblNomeUsuPresta.setText(LblNomeUsuPresta);
        this.LblNomeUsuPresta.setForeground(Color.BLUE);
        
        this.setSize(575, 650);
        
    }

    private TelaPrincipalPresta() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        LblNomeUsuPresta = new javax.swing.JLabel();
        MenuPrincipalPresta = new javax.swing.JMenuBar();
        MenuPrincipalPrestaSolici = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        MenuPrincipalPrestaAgenda = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        MenuPrincipalPrestaLembretes = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        MenuPrincipalPrestaPerfil = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        MnSairPrincPrest = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela principal prestador");
        setResizable(false);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Agendamentos", "Status", "Data da manutenção"
            }
        ));
        jTable1.setShowGrid(true);
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Total de agendamentos em aberto:");

        jLabel2.setText("Número");

        LblNomeUsuPresta.setText("Mensagens...");

        MenuPrincipalPresta.setBackground(new java.awt.Color(32, 32, 63));
        MenuPrincipalPresta.setForeground(new java.awt.Color(255, 255, 255));
        MenuPrincipalPresta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        MenuPrincipalPresta.setOpaque(true);

        MenuPrincipalPrestaSolici.setText("Solicitações");

        jMenuItem1.setText("Acessar");
        MenuPrincipalPrestaSolici.add(jMenuItem1);

        MenuPrincipalPresta.add(MenuPrincipalPrestaSolici);

        MenuPrincipalPrestaAgenda.setText("Agenda");

        jMenuItem2.setText("Acessar");
        MenuPrincipalPrestaAgenda.add(jMenuItem2);

        MenuPrincipalPresta.add(MenuPrincipalPrestaAgenda);

        MenuPrincipalPrestaLembretes.setText("Lembretes");

        jMenuItem3.setText("Acessar");
        MenuPrincipalPrestaLembretes.add(jMenuItem3);

        MenuPrincipalPresta.add(MenuPrincipalPrestaLembretes);

        MenuPrincipalPrestaPerfil.setText("Perfil");

        jMenuItem4.setText("Acessar");
        MenuPrincipalPrestaPerfil.add(jMenuItem4);

        MnSairPrincPrest.setText("Sair");
        MnSairPrincPrest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnSairPrincPrestActionPerformed(evt);
            }
        });
        MenuPrincipalPrestaPerfil.add(MnSairPrincPrest);

        MenuPrincipalPresta.add(MenuPrincipalPrestaPerfil);

        setJMenuBar(MenuPrincipalPresta);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LblNomeUsuPresta)
                .addGap(30, 30, 30))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(LblNomeUsuPresta)
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(251, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MnSairPrincPrestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnSairPrincPrestActionPerformed
        // TODO add your handling code here:
        TelaInicial telaInicio = new TelaInicial();
        telaInicio.setLocationRelativeTo(null);
        telaInicio.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MnSairPrincPrestActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalPresta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalPresta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalPresta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalPresta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new TelaPrincipalPresta().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LblNomeUsuPresta;
    private javax.swing.JMenuBar MenuPrincipalPresta;
    private javax.swing.JMenu MenuPrincipalPrestaAgenda;
    private javax.swing.JMenu MenuPrincipalPrestaLembretes;
    private javax.swing.JMenu MenuPrincipalPrestaPerfil;
    private javax.swing.JMenu MenuPrincipalPrestaSolici;
    private javax.swing.JMenuItem MnSairPrincPrest;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
