/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

import java.awt.Color;
import javax.swing.plaf.basic.BasicMenuBarUI;

/**
 *
 * @author ALUNO
 */
public class TelaGerenciamentoPresta extends javax.swing.JFrame {

    /**
     * Creates new form TelaGerenciamentoPresta
     */
    public TelaGerenciamentoPresta() {
        initComponents();
        
        this.getContentPane().setBackground(new Color(198, 200, 200));
        Color corMenu = new Color(32, 32, 63); 
        MenuGerenPresta.setBackground(corMenu);
        MenuGerenPresta.setUI(new BasicMenuBarUI());
        MenuGerenPrestaSolit.setForeground(Color.WHITE);
        MenuGerenPrestaAgenda.setForeground(Color.WHITE);
        MenuGerenPrestaLembretes.setForeground(Color.WHITE);
        MenuGerenPrestaPerfil.setForeground(Color.WHITE);
        
        this.setSize(575, 650);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu4 = new javax.swing.JMenu();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        BtnVoltarGerPresta = new javax.swing.JButton();
        MenuGerenPresta = new javax.swing.JMenuBar();
        MenuGerenPrestaSolit = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        MenuGerenPrestaAgenda = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        MenuGerenPrestaLembretes = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        MenuGerenPrestaPerfil = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();

        jMenu4.setText("jMenu4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela de gerenciamento");
        setPreferredSize(new java.awt.Dimension(575, 397));
        setResizable(false);

        jButton1.setBackground(new java.awt.Color(255, 212, 59));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(33, 40, 68));
        jButton1.setText("Solicitações");

        jButton2.setBackground(new java.awt.Color(255, 212, 59));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(33, 40, 68));
        jButton2.setText("Agendadados");

        jButton3.setBackground(new java.awt.Color(255, 212, 59));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(33, 40, 68));
        jButton3.setText("Em andamento");

        jButton4.setBackground(new java.awt.Color(255, 212, 59));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(33, 40, 68));
        jButton4.setText("Encerrados");

        BtnVoltarGerPresta.setBackground(new java.awt.Color(32, 32, 63));
        BtnVoltarGerPresta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnVoltarGerPresta.setForeground(new java.awt.Color(255, 255, 255));
        BtnVoltarGerPresta.setText("Voltar");
        BtnVoltarGerPresta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVoltarGerPrestaActionPerformed(evt);
            }
        });

        MenuGerenPresta.setBackground(new java.awt.Color(32, 32, 63));
        MenuGerenPresta.setForeground(new java.awt.Color(255, 255, 255));
        MenuGerenPresta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        MenuGerenPresta.setOpaque(true);

        MenuGerenPrestaSolit.setText("Solicitações");

        jMenuItem1.setText("Acessar");
        MenuGerenPrestaSolit.add(jMenuItem1);

        MenuGerenPresta.add(MenuGerenPrestaSolit);

        MenuGerenPrestaAgenda.setText("Agenda");

        jMenuItem2.setText("Acessar");
        MenuGerenPrestaAgenda.add(jMenuItem2);

        MenuGerenPresta.add(MenuGerenPrestaAgenda);

        MenuGerenPrestaLembretes.setText("Lembretes");

        jMenuItem3.setText("Acessar");
        MenuGerenPrestaLembretes.add(jMenuItem3);

        MenuGerenPresta.add(MenuGerenPrestaLembretes);

        MenuGerenPrestaPerfil.setText("Perfil");

        jMenuItem4.setText("Acessar");
        MenuGerenPrestaPerfil.add(jMenuItem4);

        jMenuItem5.setText("Sair");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        MenuGerenPrestaPerfil.add(jMenuItem5);

        MenuGerenPresta.add(MenuGerenPrestaPerfil);

        setJMenuBar(MenuGerenPresta);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 564, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnVoltarGerPresta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 222, Short.MAX_VALUE)
                .addComponent(BtnVoltarGerPresta)
                .addGap(84, 84, 84))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        TelaInicial telaInicio = new TelaInicial();
        telaInicio.setLocationRelativeTo(null);
        telaInicio.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void BtnVoltarGerPrestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVoltarGerPrestaActionPerformed
        // TODO add your handling code here:
        TelaPrincipalPresta tlPrincipalPresta = new TelaPrincipalPresta("");
        tlPrincipalPresta.setLocationRelativeTo(null);
        tlPrincipalPresta.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnVoltarGerPrestaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaGerenciamentoPresta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaGerenciamentoPresta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaGerenciamentoPresta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaGerenciamentoPresta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaGerenciamentoPresta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnVoltarGerPresta;
    private javax.swing.JMenuBar MenuGerenPresta;
    private javax.swing.JMenu MenuGerenPrestaAgenda;
    private javax.swing.JMenu MenuGerenPrestaLembretes;
    private javax.swing.JMenu MenuGerenPrestaPerfil;
    private javax.swing.JMenu MenuGerenPrestaSolit;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    // End of variables declaration//GEN-END:variables
}
